style/servo/selector_parser.rs
This goes along with the existing `servo-anonymous-table-cell` and
`servo-anonymous-table-row`.
=> Add `servo-anonymous-table`

style/properties/longhands/box.mako.rs
**Description**
- It is part of the [issue](https://github.com/servo/servo/issues/31875)
=> Implement baseline-source

style/servo/media_queries.rs
This will allow embedders to expose the font metrics for resolution of
font-relative units.
=> Expose a `FontMetricsProvider` interface on Device

style/properties/longhands/inherited_table.mako.rs
Co-authored-by: Martin Robinson <mrobinson@igalia.com>
=> Enable 'empty-cells' for layout 2020

Cargo.toml
These are left over from when the file was copied from Servo.
=> Remove unused workspace dependencies

style_static_prefs/src/lib.rs
Emilio suggested this as a first step toward upstreaming this crate.
=> Use a fallback "false" for `servo_static_prefs`

style/properties/longhands/inherited_table.mako.rs, style/servo/selector_parser.rs
This will allow turning off properties that are handled by the wrapper.
=> Add a -servo-table-grid pseudo and `caption-side`

style/properties/longhands/inherited_box.mako.rs, style/properties/longhands/text.mako.rs
Co-authored-by: Rakhi Sharma <atbrakhi@igalia.com>
=> servo: Add support for bidi in non-legacy layout

malloc_size_of/Cargo.toml, style/Cargo.toml
Corresponding servo PR:
- https://github.com/servo/servo/pull/33412
=> Upgrade to markup5ever 0.14 and xml5ever 0.20

style/animation.rs, style/properties/data.py, style/properties/longhands/ui.mako.rs, style/properties/mod.rs, style/properties/properties.mako.rs
Also removes some code that isn't present upstream.
=> Implement `transition-behavior`

atoms/static_atoms.txt
Needed for slotchange events in servo
=> Add `slotchange` atom

atoms/static_atoms.txt
Needed for dialog events in Servo.
=> add cancel to static_atoms

style/animation.rs
When we are trying to interpolate two values that can't be interpolated according to the animation type of the CSS property, CSS animations should always fall back to discrete interpolation, and CSS transitions should also do so when `transition-behavior` is `allow-discrete`.
Servo PR: https://github.com/servo/servo/pull/34981
=> Let animations & transitions fall back to discrete interpolation

style/Cargo.toml
Bump markup5ever version to 0.15
=> Bump markup5ever version

style/Cargo.toml
=> Specify version for remaining in-tree `style` dependencies

style/servo/selector_parser.rs, stylo_static_prefs/src/lib.rs
=> Add support for the `::marker` pseudo-element

style/Cargo.toml
Part of https://github.com/servo/servo/pull/36284
=> Bump markup5ever

style/matching.rs
Something I forgot to do earlier https://github.com/servo/stylo/pull/145#discussion_r2024499150
=> `matching.rs`: remove unnecessary `mut` specifier

style/servo/selector_parser.rs
Companion PR for https://github.com/servo/servo/pull/37307
=> Implement `::part` selector support

selectors/matching.rs, style/attr.rs, style/lib.rs, style/shadow_parts.rs
Companion PR for https://github.com/servo/servo/pull/37345
Part of https://github.com/servo/servo/issues/35349
=> Add `AttrValue::ShadowParts`

style/servo/selector_parser.rs
Companion PR for https://github.com/servo/servo/pull/38564.
=> Parse `:state` pseudo class
