servo/stylo

style/properties/build.py
Servo’s style unit tests ([tests/unit/style/properties/scaffolding.rs](https://github.com/servo/servo/blob/ef8a0b7f7be8dce5a09f771822c112692a0f9921/tests/unit/style/properties/scaffolding.rs)) rely on a css-properties.json in target/doc/servo, but now that Stylo is in its own repo, we write the file to the wrong path. This patch fixes that.
- Before patch, single repo:
/path/to/servo/components/style/properties/../../../target/doc/servo
= /path/to/servo/target/doc/servo
- Before patch, separate Stylo repo:
/path/two/stylo/style/properties/../../../target/doc/servo
= /path/two/target/doc/servo
- After patch, separate Stylo repo:
/path/to/servo/target/debug/build/style-\*/out/../../../../../target/doc/servo
= /path/to/servo/target/doc/servo
=> Fix target path for css-properties.json

style/properties/build.py
Servo’s Windows builds use CARGO_TARGET_DIR to put build artifacts on another disk, outside the main repo. The ability to override the target directory means we can’t necessarily traverse from there to ../target. This patch fixes that.
=> Fix target path for css-properties.json again

.github/workflows/sync-upstream.yml, .github/workflows/sync.yml
This patch makes the sync upstream workflow run daily, and gives it a clearer name that will distinguish it from a future workflow that syncs main into a date branch.
=> Run the sync upstream workflow daily (and rename it)

.github/workflows/main.yml, Cargo.lock, Cargo.toml
=> Add a GitHub Actions main workflow and fix the build

style/values/specified/image.rs
This was disabled in a pretty sneaky way. Servo can easily render
these with WebRender, so enable them.
=> Enable conic gradient parsing for servo

style/font_face.rs, style/properties/longhands/font.mako.rs, style/values/computed/font.rs, style_static_prefs/src/lib.rs
Servo needs these properties in order to properly load the fonts on
servo.org. In addition, remove some custom Servo code that is no longer
necessary. Servo will handle filtering web font sources internally,
which will allow it to be less dependent on Stylo for this.
This is the first step toward WOFF2 support in Servo.
=> Remove Servo-specific font code and expose font-face properties

.github/workflows/main.yml
Thus the build will fail if a PR modifies Cargo.toml but forgets to include the changes in Cargo.lock
=> Use --locked when building in CI

style/properties/longhands/font.mako.rs, style/values/specified/font.rs
This Pull Request includes the following changes:
- Modified the `helpers.predefined_type` function call for `-x-lang`, adding support for `gecko servo` engines.
- Added implementation for `XTextScale`, providing functionality for handling text scaling.
refer at [servo issue](https://github.com/servo/servo/issues/31723)
=> Enable x-lang attribute for Servo engine

selectors/builder.rs, selectors/parser.rs, servo_arc/Cargo.toml, servo_arc/lib.rs, style/properties_and_values/value.rs, style/values/computed/font.rs, style_traits/arc_slice.rs, to_shmem/lib.rs
I reverted 516aec4 because it was making Servo crash.
This relands it together with 63a6a2d3e, with avoids the crashes.
=> Reland "Bug 1842221 - Simplify ThinArc and friends"

style/properties/longhands/position.mako.rs
Adds the `start`, `end` and `space-evenly` values to the `align-content` and `justify-content` enums. I will post a Servo PR implementing support for these values in layout2020's flexbox implementation shortly.
Corresponding servo PR: https://github.com/servo/servo/pull/31724
I have made the simplest change and just added these to Servo's existing enum, but the change I would really like to make is to switch Servo over to [Gecko's content alignment implementation](https://github.com/servo/stylo/blob/main/style/values/specified/align.rs). This adds support for parsing:
- ~`auto` and~ `normal`
- `baseline`, `first baseline`, and `last baseline`
- ~`self-start` and `self-end`~
- The "safe" alignment variants that fallback behaviour on overflow
EDIT: While the `self-start` and `self-end` …
=> Add support for `start`, `end`, and `space-evenly` values to `align-` and `justify-content` properties

style/properties/data.py, style/properties/longhands/inherited_text.mako.rs, style/properties/shorthands/inherited_text.mako.rs
Split it into `white-space-collapse` and `text-wrap-mode`:
| white-space | white-space-collapse | text-wrap-mode |
| ----------- | -------------------- | -------------- |
| normal      | collapse             | wrap           |
| nowrap      | collapse             | nowrap         |
| pre-wrap    | preserve             | wrap           |
| pre         | preserve             | nowrap         |
| pre-line    | preserve-breaks      | wrap           |
| -           | preserve-breaks      | nowrap         |
Note this introduces a combination that wasn't previously possible.
=> Turn white-space into a shorthand

Cargo.lock, Cargo.toml
keyboard-types 0.7 is good because (among other things) it now includes NamedKey::F25..=F35
Part of https://github.com/servo/servo/pull/32228
=> Update keyboard-types to 0.7

style/properties/longhands/inherited_table.mako.rs
=> Enable `border-collapse` for non-legacy layout in Servo

style/properties/shorthands/text.mako.rs
This pull request is a continuation of #31, which was closed due to the need for rebasing. I have rebased my changes as requested by the maintainer.
- Updated the `sub_properties` attribute of the `text-decoration` shorthand to include `text-decoration-style` and `text-decoration-color` for the Servo engine.
- Modified the `parse_value` function to parse `text-decoration-style` and `text-decoration-color` properties when the engine is Servo. The parsed values are stored in the `style` and `color` variables, respectively.
- Updated the `ToCss` implementation to serialize `text-decoration-style` and `text-decoration-color` properties for the Servo engine.
These changes ensure that the `text-decoration` shorthand in Servo correctly parses and serializes the `text-decoration-style` and …
=> Add support of style & color for `text-decoration`

style/properties/longhands/inherited_text.mako.rs, style/properties/shorthands/inherited_text.mako.rs
This also enables `overflow-wrap` and `word-break` to non-legacy
layout, so that their interaction with `break-spaces` can be implemented
and a full implementation can be added to Servo.
Co-authored-by: Rakhi Sharma <atbrakhi@igalia.com>
=> Add support for `white-space-collapse: break-spaces`

style/values/computed/font.rs
This Servo-only function is no longer used after servo/servo#32622.
=> Remove `SingleFontFamily::from_atom`

style/properties/cascade.rs, style/properties/properties.mako.rs, style/servo/media_queries.rs, style/values/specified/font.rs, style_static_prefs/src/lib.rs
In order to do this, an interface is exposed so that the embedder can
set a default style for a device.
=> servo: Add full support for generic font families

style/properties/longhands/position.mako.rs
These lines:
- Were introduced in the "Commit all other changes from Servo" commit (I wont put a git commit id due to the frequent rebasing in this repo)
- Are `#[cfg(feature = "gecko")]`
- Are not present in upstream Stylo
I therefore conclude that we can safely remove them from our downstream copy.
I believe commit could even be squashed into the "Commit all other changes from Servo" commit next time `main` is being rebased (which would simplify the history as the change would disappear entirely rather than being introduced and then removed again).
=> Remove impl_align_conversions

style/properties/longhands/position.mako.rs, style/properties/shorthands/position.mako.rs, style/style_adjuster.rs, style/values/computed/align.rs, style/values/computed/mod.rs, style/values/specified/align.rs, style/values/specified/mod.rs
- Cherry-picked ddb7af7 from upstream
- Remove alignment style adjustment function (which should be implemented in layout anyway - implemented in servo#32686)
- Switch column-gap to being behind the flexbox flag rather than the multi-column layout flag
=> Switch to Gecko's representation of alignment styles

style/properties/longhands/position.mako.rs
So that we can implement it in Servo, starting with https://github.com/servo/servo/pull/32800.
=> Enable `aspect-ratio` for layout 2020

.github/workflows/main.yml
Previous version of `main` had modifications to the `build.rs` from upstream that manually added mako to the Python path. That difference from upstream was eliminated in order to reduce the diff we have on top of Gecko's version of Stylo. This means that `mako` must be available when compiling Stylo on CI.
=> Install mako on CI

atoms/static_atoms.txt, style/properties/cascade.rs, style/servo/media_queries.rs, style/stylesheets/font_feature_values_rule.rs, style/values/computed/font.rs, style/values/specified/box.rs, style/values/specified/color.rs, style/values/specified/font.rs, style/values/specified/image.rs, style_traits/arc_slice.rs, style_traits/owned_slice.rs
This pulls in two changes from upstream, so that the next time we
rebase, there will not be merge conflicts:
- https://phabricator.services.mozilla.com/D217563
- https://phabricator.services.mozilla.com/D218335
The reason we need to do this is that the first is an upstreaming of
code we have downstream, but with changes. This just ports these changes
to upstream.
=> Pull in D217563 and D218335 from upstream

malloc_size_of/Cargo.toml, malloc_size_of/lib.rs, style/Cargo.toml, style/context.rs, style/driver.rs
This is no longer needed and the version of `time` used is very old.
=> Remove dependency on `time`

selectors/Cargo.toml, style_traits/Cargo.toml
Both of these crates specified `size_of_test` as a dependency but were not actually using it, so I have removed the crate from the dependency list.
This change has already been made upstream so this reduces the diff.
---
With this change, the `size_of_test` crate is not used at all by crates in this repository. The `style` crate has an identical `size_of_test` macro, but it defines it itself. However, some Servo modules are currently using this crate (from this repository) so we can't delete it entirely. However I think we should consider:
- Moving it to the `servo/servo` repo.
- OR moving it to it's own repo, publishing it on crates.io and consuming it from there.
It's pretty trivial so maintenance should be easy either way.
=> Remove unused `size_of_test` dependency from `selectors` and `style_traits`

style/values/specified/text.rs
This is used to implement the following HTML specification rule about
`<th>` elements:
> User agents are expected to have a rule in their user agent style sheet
> that matches th elements that have a parent node whose computed value
> for the 'text-align' property is its initial value, whose declaration
> block consists of just a single declaration that sets the 'text-align'
> property to the value 'center'.
=> Expose `-moz-center-or-inherit` for Servo

style/values/computed/length_percentage.rs
Given that `LengthPercentage::to_used_value()` accepts an `Au`, and `NonNegativeLengthPercentage::maybe_to_used_value()` an `Option<Au>`, it didn't make much sense for `LengthPercentage::maybe_to_used_value()` to accept an `Option<Length>`.
All callers from Servo and Stylo have an `Option<Au>` that they needed to convert into `Option<Length>` in order to call this function. Gecko doesn't call it.
=> Let `LengthPercentage::maybe_to_used_value()` accept `Option<Au>`

style/properties/computed_value_flags.rs, style/stylist.rs
And then remove ignore_malloc_size_of in Stylist.
=> Derive MallocSizeOf for ComputedValueFlags

style/values/computed/length.rs, style/values/generics/length.rs, style/values/specified/length.rs
=> Enable min-content, max-content, fit-content and stretch

style_static_prefs/src/lib.rs
In #79 we forgot to set the relevant pref to true. We will be adding support for these sizing keywords in Servo, so better enable it so that we can test that it works well.
=> Enable `stretch` keyword

style_static_prefs/src/lib.rs
In #84 I forgot to enable the pref, so the shorthand was still rejecting `transition-behavior` values.
=> Allow parsing `transition-behavior` value in `transition` shorthand

style/servo/selector_parser.rs
Stylo supports these and they just need to be turned on. This change
also ensures that forgiving selector mode is turned off when parsing
selectors for the `@supports` rule.
=> servo: Add support for parsing `:is()` and `:where()`

dom/Cargo.toml, dom/lib.rs, malloc_size_of/Cargo.toml, malloc_size_of/lib.rs, style/Cargo.toml
Servo will use a forked version of `malloc_size_of` so that it does not
push depenencies down into Stylo.
Corresponding upstream change: https://phabricator.services.mozilla.com/D229764
=> Remove Servo-specific code from `malloc_size_of`

style_traits/Cargo.toml, style_traits/lib.rs
I have submitted this upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1933010
We can actually land the Servo PR without landing this first. But we might want to land anyway this to ensure that Servo doesn't regress before the next stylo sync.
Servo PR: https://github.com/servo/servo/pull/34353
=> Remove dependency on `webrender_api`

style/global_style_data.rs
This was quite straightforward (just remove the Mutex and the calls to the lock methods). And `StyleThreadPool` already internally contains an `RwLock`. Perhaps this was previously required but isn't anymore?
Reduces the diff with upstream which doesn't have this Mutex.
Servo PR:
- https://github.com/servo/servo/pull/34480
=> Eliminate thread pool mutex

style/servo/media_queries.rs
Add function to get prefers color scheme value associated with the `Device`. This helps with completing the implementation to update the color scheme from the platform theme change event, [found here](https://github.com/servo/servo/pull/34532).
Do I have to sign commits on stylo as well?
@nicoburns
=> Add getter for prefers color scheme value found on Device

style/servo/selector_parser.rs
- Fixes https://github.com/servo/servo/issues/34820
Github.com sets it's root-level CSS variables using a selector that includes a `::backdrop` pseudo selector. It's not quite this, but it's morally equivalent to `html, html ::backdrop`. And the presence of `::backdrop` causes the entire selector to fail to parse meaning that the variables never apply and styling is way off.
Changing the selector to `html, html ::non-existent-selector` causes the styles to fail to apply in Chrome too. So I think the strict parsing is correct per the spec. So I believe the only way to make this work is to implement parsing for `::backdrop`. I don't think we support creating a backdrop in a current Servo, but if we did support then we probably would support matching styles against it, so enabling the …
=> Implement `::backdrop` pseudo-element parsing

selectors/tree.rs, style/values/computed/length_percentage.rs
Submitted upstream as https://bugzilla.mozilla.org/show_bug.cgi?id=1939791, but don't want to wait for sync before posting Servo PR.
Changes made:
- Make `LengthPercentage::unpack` and the `Unpack` type it returns public. Used to access the address of the boxed `CalcLengthPercentage` value so that it can be passed into Taffy.
- Add `OpaqueElement::from_non_null_ptr`. This is used to avoid Undefined Behaviour when constructing an `OpaqueElement` from an index which is unlikely to be a valid memory address. Technically not related to `calc()` but it's a small change, and I've bundled them when submitting upstream.
This will help enable support for `calc()` values for CSS Grid containers/items in Servo.
=> API tweaks for Taffy `calc()` integration

style_static_prefs/src/lib.rs
Firefox has it enabled by default since version 128.
=> Enable relative color syntax

style/properties/properties.mako.rs, style/values/resolved/color.rs
This way the callers don't have to clone it if they don't have ownership or want to use the value later.
Servo PR: https://github.com/servo/servo/pull/35247
=> Let `resolve_color()` take its parameter by reference

style/servo/selector_parser.rs
Servo already supports this selector, it just needs to be enabled.
=> Parse `::slotted` selector

style/properties/longhands/margin.mako.rs, style/values/specified/box.rs
Enable `overflow: clip` for Servo
Enable `overflow-clip-margin` for Servo
Servo PR: https://github.com/servo/servo/pull/35103
cc: @xiaochengh
=> Enable overflow: clip and overflow-clip-margin for Servo

README.md
=> Fix README.md for "Building Servo against your local Stylo"

style/properties/longhands/box.mako.rs, style/properties/longhands/effects.mako.rs, style/properties/longhands/svg.mako.rs, style/properties/longhands/ui.mako.rs, style/values/specified/box.rs, style/values/specified/mod.rs
Needed for https://github.com/servo/servo/issues/35470
Servo PR: https://github.com/servo/servo/pull/35787
cc @xiaochengh
=> Enable will-change property for servo

style/properties/properties.mako.rs, style/values/specified/box.rs, style/values/specified/length.rs
1. Import is unnecessary as the same type is imported at the top of the file.
2. In general, you don't need to import Debug derive macro
These imports do not exist upstream so this helps to reduce the diff.
=> Remove unnecessary imports

style/properties/cascade.rs
I've been working through the diff with upstream. This import is gecko-specific code which is referenced by gecko-feature-flagged code in both our copy and upstream Stylo. As such, I think we ought to have it in our copy (it won't be compiled under the "servo" variant anyway).
=> Reinstate missing gecko-specific import

atoms/static_atoms.txt
Adding `show` static atoms for `Notification` `show` event.
ref: https://github.com/servo/servo/issues/34841
spec: https://notifications.spec.whatwg.org/#showing-a-notification step 8
=> fix: add atoms "show"

style/values/computed/length_percentage.rs
change conversion to appunit from float of percentage calcuation, prevent child box size is calculated too large.
Servo PR: https://github.com/servo/servo/pull/34714
=> Use truncation instead of rounding to resolve percentages into app units

style/Cargo.toml
The latest version of Stylo requires app_units `0.7.8`, so let's formalize that in the `Cargo.toml` (without this my build broke until I ran `cargo update` which I knew to do but other may not)
=> Bump app_units dependency to 0.7.8

stylo_config/Cargo.toml, stylo_config/lib.rs
Now the functionality exists in std we should use that rather than the lazy_static crate.
=> Replace lazy_static with LazyLock in style_config crate

style/values/generics/image.rs, style/values/specified/image.rs
This is a performance optimization from Gecko (part of the diff) that I think we ought to adopt. Partly because I doubt Gecko will accept a reversion of this upstream.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1405411
No Servo changes required.
=> Use Arc for PaintWorklet arguments

style/Cargo.toml
We probably won't be able to upstream this. But IMO it would be reasonable for us to keep this downstream. And it's a nice QoL improvement for users of the crate (and indeed for us when we want to build Stylo standalone).
=> Make servo feature default

malloc_size_of/Cargo.toml, style/Cargo.toml, style_derive/Cargo.toml, style_traits/Cargo.toml, stylo_dom/Cargo.toml
Follows on from https://github.com/servo/stylo/pull/131
I have also submitted this upstream (https://bugzilla.mozilla.org/show_bug.cgi?id=1938783) but they are still debating whether they wish to accept the change. We need it either way as it is strictly necessary for publishing to crates.io.
=> Rename upstream crates to stylo*

style/values/generics/length.rs
This is aimed at reducing the diff. We could upstream this, but as this is a non-functional change (and I believe most of the rest of the generic values use this style of long generic names), I propose we just adjust this back to match upstream.
FWIW, the long generic names confused me for a long time: why is it called `LengthPercentage` when it could really be anything? What I realised is that the "generic" values are designed to be generic specifically over the "specified" and "computed" values. So the intent of this code is the `LengthPercentage` parameter is either `values::specified::LengthPercentage` or `values::computed::LengthPercentage`. With that in mind, the `LengthPercentage` name makes more sense I think.
=> Revert renaming of generic parameter

README.md
Updated Stylo's README with the correct instructions for building Servo with local Stylo
=> Update README to reflect the correct way to compile Servo with a local Stylo

malloc_size_of/Cargo.toml, selectors/Cargo.toml, style/Cargo.toml, style_traits/Cargo.toml, to_shmem/Cargo.toml
Stylo was already using the same version of the code as a git dependency. This just pulls it from crates.io.
Servo PR:
- https://github.com/servo/servo/pull/36073
=> Upgrade to cssparser 0.35

style/properties/longhands/font.mako.rs, style/values/generics/font.rs
This enables support for controlling the axes of variable fonts. This is currently targeting Blitz whose text stack supports variable fonts. We will definitely also want this in Servo at some point, but for now I've gated this behind the `layout.unimplemented` pref as I believe Servo's font stack does not yet support variable fonts.
=> Enable `font-variation-settings` property

malloc_size_of/Cargo.toml, selectors/Cargo.toml, style/Cargo.toml, style_derive/Cargo.toml, style_traits/Cargo.toml, stylo_atoms/Cargo.toml, stylo_config/Cargo.toml, stylo_dom/Cargo.toml, stylo_static_prefs/Cargo.toml, to_shmem/Cargo.toml
Prepare Stylo for a `v0.2.0` release. Closes #95.
Before merging this and releasing we should:
This PR builds on:
- I have gone for a simple versioning scheme where all `stylo*` crates have the same version. This means we don't have to worry about breaking vs. non-breaking changes for subcrates. And it makes it simple for consumers of Stylo to work out which version of the subcrates they ought to be depending on. `selectors` and `servo_arc` are still separately versioned.
- I propose that we (permanently) keep the following diff downstream:
- Crate version numbers `version = "x.y.z"` line in `Cargo.toml`
- Dependency lines for *crates that live within this repo* (e.g. `stylo`'s dependency on `stylo_traits`, but NOT `stylo`'s dependency on `cssparser`).
This will allow us to avoid …
=> Prepare for `v0.2.0` release

malloc_size_of/Cargo.toml, style/Cargo.toml, style_derive/Cargo.toml, style_traits/Cargo.toml
This is necessary to publish `v0.2.0`.
=> Add a description field to crates missing one

style/build.rs
This seems to interfere with `cargo publish`, and this is a workaround
for that issue.
=> Do not write Python bytecode when generating properties

style/servo/selector_parser.rs
This is part of https://github.com/servo/servo/issues/36245
Servo PR: https://github.com/servo/servo/pull/36249
=> Enable parent selector (`&`)

README.md, SYNCING.md
This new version aims to be useful to a general audience who may not be familiar with Stylo. The syncing instructions have been moved to a separate file as they are only really useful for maintainers.
[Rendered](https://github.com/nicoburns/stylo/blob/68c870c202a5585981848b2ececf9c515f266ec6/README.md)
=> Rewrite README

style/Cargo.toml
I know we only just released 0.2.0 (and I'm NOT at all planning to do this for every PR), but it would be super nice to have https://github.com/servo/stylo/pull/164 (parent selector) in the initial Blitz release so I am proposing a patch release for it.
I believe the process should be quite lightweight, just:
- Approve/Merge this PR
- Run `cargo publish` on just the `stylo` crate
(I'm hoping this won't be too controversial!)
=> Prepare for Stylo 0.2.1 release

style/animation.rs
This improves the behavior of transition toggling, cancellation, and
delay. In particular, there are many improvements with how transitions
are started when replacing an existing one.
Servo PR: https://github.com/servo/servo/pull/35978
Co-authored-by: Martin Robinson <mrobinson@igalia.com>
Signed-off-by: Euclid Ye <yezhizhenjiakang@gmail.com>
=> Rework `ElementAnimationSet::start_transition_if_applicable` to be more like the specification

style/properties/longhands/border.mako.rs, style/properties/longhands/list.mako.rs, style/values/computed/image.rs, style/values/generics/image.rs, style/values/specified/image.rs
Closes #146. Reduces the size of `GenericImage` from 40 to 24 bytes by boxing `PaintWorklet` variant.
=> Box `PaintWorklet` to reduce `GenericImage` size

stylo_atoms/static_atoms.txt
This is needed for the `beforetoggle` event for `details`, `dialog` & `popover`.
=> Add before toggle atom

style/Cargo.toml, style/lib.rs, style/macros.rs, style/servo/selector_parser.rs
See https://github.com/servo/html5ever/pull/599. This should mean much less synchronisation across repos when doing html5ever upgrades. We could also consider merging the `stylo_atoms` crate into the new `web_atoms` crate which would save us maintaining it as a "diff" here.
=> Use web_atoms crate

style/properties/properties.mako.rs, style/servo/restyle_damage.rs
Servo is currently rewriting the incremental layout system. Many
`RestyleDamage` variants only applied to the old layout system, so
only keep the variants that Servo will need for the first part of
incremental layout.
=> Make `RestyleDamage` much simpler for Servo

style/properties/data.py
When a property has no restyle damage specified, to ensure proper
behavior, it's better to be conservative and do a full reflow. That way,
the addition of the `servo_restyle_damage` setting can improve the
performacne of layout, but its absence can never break layout.
=> Make the default Servo restyle damage be `rebuild_and_reflow`

style/properties/longhands/inherited_ui.mako.rs, style/properties/longhands/svg.mako.rs
- Make changes to `clip-path` no longer cause repaint-only restyle damage,
as we are splitting out stacking context tree building from display list
building and `clip-path` can cause stacking context tree changes.
- Changes to `pointer-events` can be processed during display list building and are
thus repaint only.
=> Further refine Servo's repaint-only restyle damage

style/properties/data.py, style/properties/longhands/border.mako.rs, style/properties/longhands/box.mako.rs, style/properties/longhands/column.mako.rs, style/properties/longhands/counters.mako.rs, style/properties/longhands/effects.mako.rs, style/properties/longhands/font.mako.rs, style/properties/longhands/inherited_box.mako.rs, style/properties/longhands/inherited_table.mako.rs, style/properties/longhands/inherited_text.mako.rs, style/properties/longhands/list.mako.rs, style/properties/longhands/margin.mako.rs, style/properties/longhands/padding.mako.rs, style/properties/longhands/position.mako.rs, style/properties/longhands/svg.mako.rs, style/properties/longhands/table.mako.rs, style/properties/longhands/text.mako.rs, style/properties/properties.mako.rs, style/servo/restyle_damage.rs
This restyle damage is used in cases where we need to reconstruct the stacking contexts, because a style change has caused a box to establish or stop establishing a stacking context, but it's unnecessary to rebuild the box tree.
Additionally, `ServoRestyleDamage::REBUILD` is renamed to `REBUILD_BOX`, and old `servo_restyle_damage` values are removed in favor of it.
Servo PR: https://github.com/servo/servo/pull/37088
=> Add `ServoRestyleDamage::REBUILD_STACKING_CONTEXT`

style/properties/longhands/box.mako.rs, style/servo/restyle_damage.rs
In many cases, changes to transforms do not require rebuilding the box
and laying out again. This change uses RECALCULATE_OVERFLOW restyle damage
in these cases, except when the presence of a transform changes. In those
cases we need to rebuild the box tree.
=> Have transform and related changes conditionally trigger only overflow damage

style/thread_state.rs
I profiled servo loading a local copy of https://html.spec.whatwg.org and saw around 15% of the time being spent in `style::thread_state::get()`. Most calls are inside assertions, so they likely go away in a production build, but that's still way too much time. Arguably we shouldn't assert on the thread state that much in the first place, especially given that layout and script are now in the same thread, but replacing the `RefCell` with a `Cell` already takes the time down to 10%.
Additionally, this change renames all one-letter variables for clarity and removes the `thread_types` macro because it is unnecessary (Removing it *decreases* the LoC!)
I wasn't sure whether I should submit the patch here or upstream, but gecko doesn't use the thread state so i figured this repo was the right …
=> Use `Cell` instead of `RefCell` for storing `ThreadState`

.github/workflows/sync-upstream.yml, sync.sh
The `main` branch is used by the upstream Firefox repository, so use
that everywhere.
=> Correct some issues with the sync script

style/properties/properties.mako.rs, style/servo/restyle_damage.rs
Changes made:
- Convert `restyle_damage_*` macros to plain functions.
- Rather than passing the `damage` object, a `RestyleDamage` flag to apply, and an optional extra condition, we make the return a boolean and handle the rest in regular code.
- Use `if-else` instead of `||` for short-circuiting.
Servo PR https://github.com/servo/servo/pull/38465
=> Simply restyle damage macros (and convert them to be plain functions)

style/values/generics/length.rs, style/values/specified/length.rs, stylo_static_prefs/src/lib.rs
This keyword is de-facto required for web compatibility, Firefox is also enabling it (https://bugzil.la/1988938).
Servo will just alias it to `stretch`.
Servo PR: https://github.com/servo/servo/pull/39492
=> Add support for `-webkit-fill-available` sizing keyword

style_traits/Cargo.toml
We are already doing this (and maintaining the patch) for the `stylo` crate. This wasn't previously necessary for `stylo_traits`, but that crate now also requires one of (servo, gecko) in order to compile.
=> Make servo feature default for `stylo_traits`
